# Generated by Django 3.0.4 on 2020-03-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_created_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='creator',
            new_name='created_by',
        ),
    ]
